### ISSUE TITLE
Update to use the new revised standard test interface

### ISSUE THREAD

**Issue by rasibley** [bgoncalv/upstream-testing-vagrant#1]
The standard test interface has been revised to use Ansible dynamic inventory scripts:
https://fedoraproject.org/wiki/CI/Tests
https://fedoraproject.org/wiki/Changes/InvokingTests

Update the Vagrantfile to run in the correct context using tags from tests.yml, for example if the container tag is included in the tests.yml file, then proceed to run it inside a container:

(Atomic)
sudo ANSIBLE_INVENTORY=$(test -e inventory && echo inventory || echo /usr/share/ansible/inventory) TEST_SUBJECTS=../atomic.qcow2 TEST_ARTIFACTS=$PWD/artifacts ansible-playbook --tags atomic tests.yml

(Docker)
sudo ANSIBLE_INVENTORY=$(test -e inventory && echo inventory || echo /usr/share/ansible/inventory) TEST_DEBUG=1 TEST_SUBJECTS=docker:docker.io/library/fedora:26 TEST_ARTIFACTS=$PWD/artifacts ansible-playbook --tags container tests.yml

(Classic)
sudo ANSIBLE_INVENTORY=$(test -e inventory && echo inventory || echo /usr/share/ansible/inventory) TEST_SUBJECTS="" TEST_ARTIFACTS=$PWD/artifacts ansible-playbook --tags classic tests.yml

**Comment by bgoncalv** [comment]
The idea is to use vagrant only for classic mode. So I've added only the command needed by it.
